### ISSUE TITLE
Deixar posts dinamicos

### ISSUE THREAD

**Issue by reginaldojunior** [BrunoKinoshita/ladies-coding#3]
Por que não criar uma área de cadastro de usuários onde eles podem fazer as postagens dos eventos ?

Tipo, eu me cadastro no ladies-coding e lá eu posso cadastrar vários eventos, e fazer uma moderação com um super admin para que ele consiga aprovar, excluir ou editar um post antes de ir para o site final.

Caso queira fazer algo assim me disponibilizo para fazer o back-end.

**Comment by BrunoKinoshita** [comment]
No need for that.
